iddan/react-spreadsheet

__tests__/matrix.test.js
package.json
src/Cell.js
src/DataViewer.js
src/Spreadsheet.css
src/Spreadsheet.js
src/matrix.js
stories/index.js
yarn.lock

Formulas Support

---

__tests__/matrix.test.js
src/matrix.js
stories/index.js

Using a safe Matrix.reduce() to preserve matrix shape.

WIP: Accurate Matrix

---

src/Spreadsheet.js

This implements https://github.com/iddan/react-spreadsheet/issues/32 – it was straightforward enough!

make ColumnIndicator and RowIndicator overrideable

---

src/Spreadsheet.js

@iddan sorry for the double work 😞

completely missed the adjustment back to using this.formulaParser

---

src/DataViewer.js
src/Spreadsheet.js
src/util.js

Fixes https://github.com/iddan/react-spreadsheet/issues/79

Fix computations for values being derived from derived values

---

src/actions.ts

Using react-spreadsheet in a project and wanted this, then I saw it was an open issue. :)

Add shift-tab handling to go left one cell. Fixes #88

---

package.json
rollup.config.js
src/ColumnIndicator.tsx
src/CornerIndicator.tsx
src/Row.tsx
src/RowIndicator.tsx
src/Spreadsheet.tsx
src/Table.tsx
src/matrix.ts
src/types.ts
tsconfig.json
yarn.lock

Bundle TypeScript declarations so when a user goes to a definition of the library it would be from the same module.

Bundle type declarations for better introspection

---

package.json
src/__mocks__/style-mock.ts
yarn.lock

Load CSS in Jest tests as a first step towards visual regression testing

Load CSS in Jest tests

---

src/reducer.test.ts
src/reducer.ts

Clear cell with Delete key

---

src/Cell.tsx

Fixes https://github.com/iddan/react-spreadsheet/projects/1#card-8682375

Auto resizing edit cell

---

src/Spreadsheet.css

Fix data editor width

---

website/docs/get-started.md

Add scheduler to installation command on website

Add scheduler to installation command on website

---

src/reducer.ts

Fix cell clean, preserve cell info and prevent when readonly. fixes #228 #229

---

src/matrix.test.ts
src/matrix.ts
src/reducer.ts

This issue is documented in https://github.com/iddan/react-spreadsheet/issues/232. I ran into the same issue recently.

Fix the problem when copy paste the number of columns are not increased.

---

src/Cell.tsx
src/ColumnIndicator.tsx
src/CornerIndicator.tsx
src/RowIndicator.tsx
src/Selected.tsx
src/Spreadsheet.tsx
src/point-range.ts
src/reducer.test.ts
src/reducer.ts
src/selection.test.ts
src/selection.ts
src/util.test.ts
src/util.ts

Make Selected a class with subclasses describing each type of selection. This should make it better for exposure to external usage.

New Selected API

---

src/reducer.ts

Support pasting 1 cell to multiple cells

---

src/reducer.ts

Cut should delete from the copied range, not 0,0

Fix cut deletion

---

website/docs/usage.md

The website I accessed was not having enough documentation and I personally found it difficult to find references on how to use controlled and custom rows/ columns.
So I added it by myself and created this request. I would love to contribute more to this project.

Improve website API reference

---

src/Spreadsheet.test.tsx
src/engine/engine.ts
src/engine/point-graph.spec.ts
src/engine/point-graph.ts

Fix Formula Evaluation

---

website/docs/02-usage.md

I'm new to react-spreadsheet.
To understand the library, I copy the code in the document. When I copy the code of [Controlled Section in Usage](https://iddan.github.io/react-spreadsheet/docs/usage#controlled), I get the following error.
I posted [the issue](https://github.com/iddan/react-spreadsheet/issues/416)

fix the document of usage for typescript
