iddan/react-spreadsheet

src/SpreadsheetStateProvider.js
I think this is really helpful for keeping your track of individual cells, when having an external aggregator that has to sanitize new info. It's also backwards compatible so it doesn't affect any of the current dependants
=> Added active coordinates onCellCommit

src/Spreadsheet.js
I'm doing some prototyping with `react-spreadsheet` (fantastic component BTW, thank you for creating it!). I'd like to be able to define custom formulas. This is possible with `hot-formula-parser` but access to the `formulaParser` instance is needed.
Passing a `prop` to customize the instance used by a `Spreadsheet` component seemed like the best solution.
=> Enable custom FormulaParser via props

src/ActiveCell.js, src/bindings.js
Currently, only first level of bindings are returned. For example:
A1 = 10
A2 = `=A1`
A3 = `=A2 * 2`
for A3 bindings it'd only return A2, however, A2 has its own set of
dependents, they should be returned as well. This commit fixes that.
=> Fix bindings, return all level of dependents, instead of just first

package.json
After build, the types file is generated within the `dist` directory.
Currently it is unable to find the types when importing:
=> Fix path to types file

src/SpreadsheetStateProvider.tsx
The component stores the callback function as they are on component mount, but this is not compatible with functional component callbacks, since the stored callback contains stale references to component state. To solve this, I just delay fetching the callback functions to when a store event occurs, so the latest callback function is always used.
=> Fix bug with outdated callback functions

src/actions.ts
I can not paste empty string (to override existing cell value).
When pasting empty string `""`, `!text` returns true.
I think `!text` filter is no longer necessary, isn't it?
Thanks!
=> Allow to paste empty string

src/HeaderRow.test.tsx, src/HeaderRow.tsx, src/Spreadsheet.tsx, src/types.ts
I added some new properties to the `Row` when rendering. Another way to implement this feature is to create a separated component `HeaderRow` in order to fully differentiate table body row and table header row.
=> Make it possible to differentiate column row / content row 

src/reducer.ts
Currently, if you enter 'delete' key on a cell, the cell itself in 'state.data' will be overridden with undefined which also delete the whole cell information including not only 'value' but DataEditor, DataViewer, and className. 
In order to prevent this, I just updated the clear action as it can override only a value property with undefined.
=> update: maintain cell info when deleting value

src/matrix.test.ts, src/matrix.ts
The `Matrix.toArray` function does not properly flatten non-square matrices to an array. This results in incorrect range returned by the default `getCellRangeValue`, which in turn results in the formulas getting incorrect arguments.
---
This PR adds the tests for the non-square matrices flattening and fixes the issue of looping the matrix columns incorrect amount of times due to the number of rows not matching the number of columns in non-square matrices.
=> Fix Matrix.toArray

src/Cell.test.tsx, src/Cell.tsx, src/DataViewer.test.tsx, src/Spreadsheet.tsx, src/stories/CustomCell.tsx, src/types.ts
This PR adds ability to set cell data from the viewer component. It allows users to create cells with controls, eg. checkboxes:
https://user-images.githubusercontent.com/6833443/169305427-da567895-7615-4aff-91df-1c984eadec71.mp4
https://user-images.githubusercontent.com/6833443/169305435-c69c3829-fc6f-447e-97e3-7978df2b3ab5.mp4
=> Allow data to be set in viewer

src/Spreadsheet.tsx
The `lastChanged` state property seems to contain the real coordinates to the cell which was last changed as opposed to the `active` property which may differ from the cell that was last changed if the user has selected a different cell. 
Resolves #83.
=> Use lastChanged for onCellCommit coordinates

package.json
I think flatmap’s typings may be under `dependencies` by accident. This change does not affect the lockfile under Yarn classic.
=> Move types to devDependencies

src/ActiveCell.tsx, src/Cell.tsx, src/Spreadsheet.tsx, src/actions.ts, src/engine.ts, src/formula.ts, src/index.ts, src/reducer.ts, src/types.ts, src/typings/fast-formula-parser.d.ts, website/docs/formula-parser.md
Added:
- FormulaParser override (and added example to readme)
- Formula override as per fast-formula-parser
- Some renaming to make things consistent
- Error log of formula validation while editing (see issue [321](https://github.com/iddan/react-spreadsheet/issues/321))
=> Exposing formula parser and some minor fixes

src/index.ts
We have a formula input in a separate component in which we want to use the data from the spreadsheet as our model.
The problem we have is that the data is, logically, not evaluated and it will still contain formulas, resulting to a formula string instead of an evaluated number.
If we want to evaluate the formula outside of the data, we need to use the Model class.
This class already has the dependency graph and the evaluation of the data, so that should be it
Local tests show that this change is enough to allow external formulas to be evaluated over the data, even nested formulas (e.g. External: '=A1+A2', A1: '=2+3', A2: '=2*A1' results in 15)
It would be great if the Model is exported from the root index.ts, hence this PR.
=> QOL change: Export Model class

src/DataViewer.tsx, src/Spreadsheet.css, src/matrix.test.ts, src/matrix.ts, src/reducer.ts, src/util.ts
> When copying content from a CSV for pasting, if there are line break indicators within the content, pasting it into `<Spreadsheet />` creates a new row due to these indicators. This PR is submitted to improve this behavior.
When copying content like the one shown above from Google Sheets, it becomes a string like the following, with line break entities (`\n`) inside double quotes:
```
// Content copied from a Google Sheets cell
"this is first line.
this is second line."
```
Pasting such CSV content into `<Spreadsheet />` interprets double quotes as text and creates two rows due to the included line break indicators, even though the actual content has line breaks within the cell. The goal is to generate only one row (to-be).
|as-is|to-be|
|---|---|
|<img width="400" alt="image" …
=> Enhance <Spreadsheet /> to Properly Handle Line Breaks Inside Quotes in CSV Pasting

src/Spreadsheet.test.tsx, src/Spreadsheet.tsx
Issue #338: Added getEvaluatedData prop to expose the result of the formula
=> Issue #338: Added onEvaluatedDataChange  prop to expose the result of the formula

src/reducer.ts
Proposal to address https://github.com/iddan/react-spreadsheet/issues/394
=> Clear cell contents when single cell is selected but not editing

src/reducer.ts
Proposal to address https://github.com/iddan/react-spreadsheet/issues/393
A small change to wrap around to a new row and the first column if you're at the last column.
=> Tab key press wraps around to next row

website/docs/02-usage.md
The heading itself has an id of "controlled", with a lowercase "c". In chrome (and probably other browsers), these anchors are case-sensitive.
=> Fix heading anchor link

src/Spreadsheet.test.tsx, src/Spreadsheet.tsx, src/index.ts, src/stories/Spreadsheet.stories.tsx
Enhance Spreadsheet component with ref support and add related tests
- Introduced `SpreadsheetRef` type to expose an `activate` method for cell activation.
- Updated `Spreadsheet` component to support forwarding refs and added memoized methods.
- Enhanced tests to cover new ref methods, ensuring they are stable and handle invalid points gracefully.
- Added a new story for controlled activation demonstrating the use of the ref.
**This update improves the usability of the Spreadsheet component by allowing parent components to programmatically activate cells.**
=> Expose activate method
